[project]
name = "falconbot"
version = "0.1.0"
description = "A discord bot for verification management"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nextcord>=2.6.0",
    "setuptools>=75.6.0",
]
